### ISSUE TITLE
Conflicts with Webserver.h on some HTTP declarations

### ISSUE THREAD

**Issue by Bjack795** [Pedroalbuquerque/ESP32WebServer#2]
#### Hardware
**Esp8266/Esp32:**
- [ ] ESP8266
- [X] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [ ] ESP12 E/F/S (nodemcu, wemos, feather)
- [X] Other (Wemos D32 pro)

### Description
There are conflicts between this library and the Webserver.h library.
The compiler tells me that there are some declarations done by both about the HTTP parts of the code.
I have to use both libraries since I have two sublibraries referring one to ESP32Webserver.h and the other to Webserver.h.
Is there any chance to solve this incompatibility?

### Debug Messages
- using typedef-name 'HTTPMethod' after 'enum'?
 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

- 'HTTPMethod' has a previous declaration

- redeclaration of 'HTTP_ANY'
 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

- previous declaration 'HTTPMethod HTTP_ANY'

- redeclaration of 'HTTP_GET'

- previous declaration 'HTTPMethod HTTP_GET'

Etc...

**Comment by Pedroalbuquerque** [comment]
Hi Bjack795,

this library can be found on ivan repository, so maybe he can provider better help from the inside of the library.

name=ESP32WebServer
version=1.0
author=Ivan Grokhotkov
maintainer=Ivan Grokhtkov <ivan@ESP32.com>
sentence=Simple web server library
paragraph=The library supports HTTP GET and POST requests, provides argument parsing, handles one client at a time.
category=Communication
url=
architectures=ESP32


anyway I have faced similar problems as you described, and my solution was to change the #include to use a single library, not both.
