### ISSUE TITLE
Can we introduce this into the Arduino IDE Library Manager somehow?

### ISSUE THREAD

**Issue by MaxValue** [Pedroalbuquerque/ESP32WebServer#3]
Would be nice to have.

**Comment by Pedroalbuquerque** [comment]
Hi Maxvalue, can you elaborate a bit more, I did not get what you are proposing. I may miss some context.

**Comment by Pedroalbuquerque** [comment]
maybe you meant to add ESP32WebServer library to the list exposed by Arduino IDE library Manager.
If that is the case , maybe this article can help

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by MaxValue** [comment]
Yes, that is what i meant.

Hm, i skimmed over the requirements, it should be doable, but we would have to check first and of course add all of those necessary metadata files.

**Comment by Pedroalbuquerque** [comment]
for now I am note able to invest enough time to bring this to Arduino IDE library Manager.
