### ISSUE TITLE
Can you explain this.

### ISSUE THREAD

**Issue by arnold-b** [Pedroalbuquerque/ESP32WebServer#4]
Hello, i dont understand this declaration. Can you explain just what it do ? Thanks

It looks like you call function and set the values. 
if it is like this than i didn´t know this kind of syntax

ESP32WebServer::ESP32WebServer(int port)
: _server(port)
, _currentMethod(HTTP_ANY)
, _currentVersion(0)
, _currentStatus(HC_NONE)
, _statusChange(0)
, _currentHandler(0)
, _firstHandler(0)
, _lastHandler(0)
, _currentArgCount(0)
, _currentArgs(0)
, _headerKeysCount(0)
, _currentHeaders(0)
, _contentLength(0)
, _chunked(false)
{}

**Comment by Pedroalbuquerque** [comment]
Hi arnold-b , 

in fact as you may check on the source is from IVAN (visit IOTSHARING.COM for more).

I am not familiar with syntax but I took the same assumption as you, it is just assigning variables some values.

**Comment by arnold-b** [comment]
Thank you

 

Von: Pedro Albuquerque <notifications@github.com> 
Gesendet: Montag, 11. März 2019 05:29
An: Pedroalbuquerque/ESP32WebServer <ESP32WebServer@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Pedroalbuquerque/ESP32WebServer] Can you explain this. (#4)

 

Hi arnold-b ,

in fact as you may check on the source is from IVAN (visit IOTSHARING.COM for more).

I am not familiar with syntax but I took the same assumption as you, it is just assigning variables some values.
